name: subs-puller
author: dongchengjie
description: A github action designed for pulling subscribe files.

inputs:
  repository:
    description: 'Github repository(should contain both owner and repo,default: current repository)'
    required: false

  branch:
    description: 'Github branch(default: current branch)'
    required: false

  token:
    description: 'Github token(requires access to workflows)'
    required: true

  config:
    description: 'Config file(url is supported)'
    required: true

  merged:
    description: 'Where merged proxy-provider file is saved'
    required: false

runs:
  using: docker
  image: Dockerfile

branding:
  color: blue
  icon: send
